### ISSUE TITLE
Theme doesn't show up in Package Manager

### ISSUE THREAD

**Issue by shaunsingh** [mauroreisvieira/moonlight-sublime-theme#1]
Hey! just wanted to let you know your theme doesn't show up in the package manager in ST4, when searching for moonlight. I

Installing manually still works as expected, and the theme is beautiful, thanks for your work.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/119268470-29d77380-bbc1-11eb-9175-10aef66c98e2.png">

**Comment by mauroreisvieira** [comment]
Hey @shaunsingh finally fixed.

**Comment by ChuksFestus** [comment]
nope, not fixed yet. still doesn't show up
